-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3308
-- Generation Time: Jun 19, 2020 at 05:18 PM
-- Server version: 5.7.28
-- PHP Version: 7.2.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `laraquiz`
--

-- --------------------------------------------------------

--
-- Table structure for table `ocr`
--

DROP TABLE IF EXISTS `ocr`;
CREATE TABLE IF NOT EXISTS `ocr` (
  `OCR_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Image_Dir` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Image_Text` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Image_Traversed` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Image_Conversion` varchar(10000) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Image_Remote` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`OCR_id`)
) ENGINE=MyISAM AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `ocr`
--

INSERT INTO `ocr` (`OCR_id`, `Image_Dir`, `Image_Text`, `Image_Traversed`, `Image_Conversion`, `Image_Remote`, `created_at`, `updated_at`) VALUES
(1, '393279924.jpg', 'Processed', 'Read', 'SCHEME OF STUDIES\r\nFOR SSC (CLASSES IX-X)\r\nCOMPULSORY SUBJECTS FOR ALL STUQEYCS (500 marks)\r\n2.\r\n3.\r\n4.\r\nEnglish (Compulsory)\r\nUrdu (Compulsory)\r\nIslamic Education/Ethies (for Non-Muslims)\r\nPakistan Studies\r\nmarks)\r\n2 papers\r\n2 palxrs\r\n2\r\n2 paper\r\n150 mark\r\n150 mark\r\n100 mark\r\n100 mark\r\nThe students will choose one of the following (A), (B) and (C) Groups carrying 600 marks:\r\n(A)\r\n(B)\r\nGroup:\r\nPhysics, Chemistry, Mathematics, Biology/Computer Sciencerrechnical Subject\r\nHumanities Group:\r\nGeneral Science, General Mathematics, Two Social Science Subjects/One Social Sci\r\nSubject and One Technical Subject\r\nIEEbnical Group:\r\nGeneral Science, General Mathematics, Two Technical Subjects\r\nLIS! OF SOCIAL SCIENCE\r\n2.\r\n4.\r\nComputer Science\r\nIslamic Studies\r\nIslamic History\r\nEconom\r\nEducation\r\nCivics\r\nClothing & Textile\r\nHealth & physical Education\r\nLIST OF TECHNICAL SUBJECTS\r\nl. Electrical Wiring\r\n3. Wood Working & Furniture Making\r\n5. Welding (ARC & GAS)\r\n7. Dress Making & Fashion Designing\r\n9.\r\n10.\r\n12.\r\n13.\r\n14.\r\nIS.\r\n2.\r\n4,\r\n6.\r\nElements of Home Economics\r\nFood and Nutrition\r\nEnglish Literature\r\nA rabie\r\nArt and Model Drawing\r\nGeography\r\nCommercial Geography\r\nComputer Hardware(Orientation)\r\nFood Processing and Preservation\r\nMotor Winding\r\nNote: The question paper will comprise three sections:\r\n- Section-A 20% MCQs. It will be compulsory and collected after prescribed time.\r\n- Section-B 50% short answers questions.\r\n- Section-C 30% long/essay type questions\r\n', 'YES', NULL, '2020-06-14 04:52:02'),
(2, '1405957548.JPG', 'Processed', 'Read', 'TYPE 111: SENTENCE COMPLETI( N USING APPROPRIATE FILLER\r\nTYPE-I\r\nSENTENC E COMPLETION USING VOCABULARY\r\nPart A: Selecting the appr opriate word from five alternative provided.\r\nLearn by Example\r\nSome people\r\nthemselves into believing that they are indispensable to the organisation they\r\nwork for.\r\n(A) Keep (B) Foo\r\n(C) Force (D) Denigrate (E) Delude\r\nAnswer: The correct word must be \'delude\". So answer is (E).\r\nDirections: Pick out the most effective word from the given words to fill in the blanks to make the entence\r\nmeaningfully complete.\r\nKamal\'s friends had nothing to offer him other than\r\nin his grief.\r\n2.\r\n4.\r\n5.\r\n6.\r\n7.\r\n8.\r\n(A)\r\nSolutic n\r\n(C)\r\nFriendship\r\n(E)\r\nHappi ess\r\nThere is no doubt t tat one has to keep\r\n(A)\r\nPace\r\n(E)\r\nTurf ng\r\nConsolation\r\n(B)\r\n(D) Kindness\r\nwith the changing times.\r\nHimself\r\n(B)\r\n(D) Oneself\r\nBelying has motl er\'s worries, Amir\'s behaviour throughout the function wa\r\nImt ginable\r\nIm odest\r\n(C)\r\nI pervious\r\n(E)\r\nAfter reaching New York, Azhar will have to\r\nS ibmit\r\n(C) Mix\r\n,cquaint\r\n(E)\r\nDowry is no ongerpermitted by law even in\r\nBlatural\r\nLove\r\n(C)\r\nPolygamous\r\n(E)\r\n(B) Imperial\r\n(D) Impecca\r\nhimsel(\'hhe new surroundings.\r\nAdapt\r\n(B)\r\n(D) Develop\r\nmarriage.\r\nBigamous\r\n(B)\r\n(D) Conventional\r\nResearch has the illusion that childhood dreams are pure Innocence.\r\nDispelled\r\nAccepted\r\nEstablished\r\n(E)\r\nEveryo e should\r\nBrace\r\n( ) Vaccinate\r\nInoculate\r\nHo much did it\r\nCost\r\nCharge\r\n(C)\r\nDiscovered\r\n(B)\r\n(D) Obse ed\r\nhimself against illness since medical care (tas now become, expensive.\r\nto reach Bombay by car?\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\nInsure\r\nEstimate\r\nPrice\r\n', 'YES', '2020-06-14 02:51:19', '2020-06-14 06:38:37'),
(3, '1586118572.PNG', 'Processed', 'Read', 'Pay\r\n9.\r\n\'he departmental inquiry. it was denied that the police had committed any\r\n11.\r\n12.\r\n13.\r\n14.\r\nunder custody.\r\nBlunder\r\nInjunes\r\nExcesses\r\nrhe petition before the Court prayed for\r\nmanagement.\r\nposting\r\nGranting\r\nDismissing\r\nMan power is the\r\nmeans •Icon verting Other\r\n(A) Indivisible\r\n(C) Insuperable\r\n(E) Inequitable\r\nam Riven to\r\nthat you are going abroad.\r\nB)\r\n(A) Predict\r\n(C) Learn\r\n(E) Apprehend\r\n(B)\r\nby people \'s perception it seems that democracy\r\n(A) Making\r\n(C) Following\r\n(E)\r\nLiked\r\nThe passengers and Crew members of the\r\nYfD)\r\nthe appointment orders issued by the\r\nQuashing\r\nRernoving - • ,\r\nto mankind\'s and\r\nIndisgrnsable\r\nInimitable\r\nUnde\r\ni\' Pakistan.\r\nPlanned\r\ning\r\nfrom the way.\r\nLittle\r\n(C)) Narrow\r\n) Better\r\nHe very successfully\r\nall\r\nall\r\n(A)\r\n(C)\r\n(E)\r\nRetaliated\r\nExtricated\r\nProtected\r\nhad a *hen it s•as taking of\r\nBrief\r\n) Large\r\nveled against him.\r\n(B) Rebutted\r\n(D) Eradicated\r\n', 'YES', '2020-06-14 06:38:05', '2020-06-15 00:26:49'),
(8, '1290923912.jpeg', 'Processed', 'Unread', 'TYPE-II\r\nSENTENCE COMPLETION USING GRAMMAR\r\nLearn by Example\r\nGenius does what it must, and talent does what it\r\n(B) Would\r\n(A) Can\r\n(D) Should\r\n(C) May\r\nAnswer: The correct word is •can\'. Hence the answer is (A).\r\n14.\r\nq.\r\n-10.\r\n17.\r\n18.\r\n19,\r\n2.\r\n3.\r\n4.\r\n5.\r\n6.\r\n7.\r\n8.\r\n9.\r\n10.\r\n11.\r\nThe passengers were very happy\r\n(A) From\r\nBy\r\nThe igheryou go, the more difficult it\r\nIs becoming\r\n(A)\r\n(C) Has become\r\nthe friendly and warm treatment given to them\r\n(B) To\r\n(D) About\r\nto breathe.\r\n(B) Became\r\nBecomes\r\nwith us.\r\nThe children were disappointed because they had hoped\r\nTo had gone\r\n(A)\r\n(C)\r\nShe stood\r\n(A)\r\n(E)\r\n(B)\r\nWould have gone\r\nTo go\r\nTo have gone\r\nAhsan, but could not utter a single wordfor quite sbme time.\r\nBefore\r\nAbout\r\nFor\r\nTowards\r\n[trust most.\r\nHe is the friend\r\n(A) Which\r\n(C) Him\r\nYou must dispense\r\nW ith\r\nIn\r\nhis service.\r\n(D)\r\n(B)\r\n(D)\r\nseveral times before I answered it.\r\nThe telephone\r\n(A) Has rung\r\n(C) Would ring\r\nI shall not desert him\r\nBy\r\n(A)\r\n(C) With\r\nall the world.\r\n(B)\r\n(D)\r\nTo\r\nWho\r\nWhom\r\nOf\r\nAt\r\nWas ringing\r\nHad rung\r\nFor\r\nFrom\r\nI bought a new car last year, but I\r\nmy old car yet, so at present I have two cars.\r\nHave sold\r\n(A)\r\n(C) Could not sell\r\nNo sooner did he go in\r\n6) Than\r\n(C) Then\r\nhe came out.\r\nDid not sell\r\nO) Have not sold\r\n(B) And\r\n(D) When\r\nThe judge acquitted the prisoner\r\n(A) About\r\nO Of\r\nthe charge of murder.\r\nAn argument\r\nbetween the two friends.\r\nBroke out\r\n(A)\r\n(B)\r\n(D)\r\n(B)\r\nFrom\r\nWith\r\nBroke in\r\n', 'YES', '2020-06-15 00:29:39', '2020-06-15 00:30:07'),
(11, '2136802986.jpeg', 'Unprocessed', 'Unread', 'N/A', 'YES', '2020-06-16 09:40:00', '2020-06-16 09:40:14'),
(12, '1718973147.jpeg', 'Processed', 'Unread', 'Sprang up\r\n(D) Rose up\r\nWhen was a child, I\r\nto school everyday instead of going by cycle,\r\n(A)\r\nHad walked\r\n(C) Walked\r\nNobody has come to see us\r\n(0) Since\r\n(C) When\r\nHe ran\r\n(4b Quickly\r\n(C) Quick\r\nIn Bush, Saddam was up\r\n(A)\r\nInto\r\nTo\r\nThe doctor advised him to go\r\n€X•) Through\r\nUnder\r\n(B) Have walked\r\n(D) Have been walking\r\nwe bought these fierce dogs.\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\nmore than his match.\r\n(B)\r\nO)\r\nseveral medical tests.\r\n(B)\r\n(D)\r\nFor\r\nTill\r\nSo quickly\r\nSo quick\r\nFor\r\nAgainst\r\nInto\r\nAbout\r\nIf you persist in telling lies to me I shall sue you\r\nslander.\r\nFor\r\n(C) With\r\nThe waiter hasn \'t bought the coffee\r\nUp\r\n(A)\r\nStill\r\n(C)\r\n(B) On\r\n(D) To\r\nI\'ve been here an hour already.\r\nTill\r\n(B)\r\nYet\r\n', 'YES', '2020-06-16 09:42:49', '2020-06-16 09:43:28'),
(13, '186317114.jpeg', 'Processed', 'Unread', 'Purpose relationship\r\n(A) Hook: Fish\r\n(C) Games: Sports\r\n:orrect answer is (A)\r\nExample Glove: Balls as\r\n(B) Winter: Weather\r\n(D) Stadium: Seats\r\nThe purpose of glove is to help in catching the ball and the purpose of hook is to catch fish. The\r\n\'Ct answer is (A)\r\nCause and effect relatlonshlp_Example Race: Fatigue as:\r\n(A) French: Athlete\r\n(B) Fast: Hunger\r\n(C) Art: Bug\r\n(D) Walking: Running\r\nThe correct answer is (B) because fatigue is the effect of race; hunger is the effect of fast.\r\nPart whole relationship Example Snake: Reptile as\r\n(A) Patch: Thread\r\n(B) Removal: Snow\r\n(C) Struggle: Wrestle\r\n(D) Hand: Clock\r\nAction to object and object to action relationship, Examples\r\nA. Kick: Football:\r\n(A) Kill: Bomb\r\n(C) Question: Team\r\nB. Steak: Broil:\r\n(A) Bread: Bake\r\n(C) Wine: Pour\r\n(B) Break: Pieces\r\n(D) Smoke: Pipe\r\n(B) Food: Sell\r\n(D) sugar: spill\r\nKick shows action and Football the object of action. This very relationship is represented in (D) i.e.,\r\nis action and pipe is the object. For B answer is (A).\r\n', 'YES', '2020-06-16 10:24:10', '2020-06-16 10:24:38'),
(14, '1431907175.jpeg', 'Processed', 'Unread', 'Synonym relatlonshlp—\r\nnormous: Huge as\r\n(A) Rough: Rock\r\n(C) Purse: Kitchen\r\nanswer iS (A\r\n(B) Muddy: Unclear\r\n(D) Black: White\r\nThe correct answer is (B) because \"muddy\" and unclear are synonyms.\r\nAntonym relationship— Example——\r\nPurity: Evil as\r\n(A) Suavity: Bluntness\r\n(C) Angle: Horns\r\n(B) North: Climate\r\n(D) Boldness: Victory\r\nThe correct answer is (A) because the two words are antonyms.\r\nPlace relationship—Example— Faisal Mosque: Islamabad as\r\n(A) Red Square: Moscow\r\n(B)Albany: New York\r\n(D) Pakistan: Nepal\r\n(C) India: Madras\r\nFaisal Mosque is situated in Islamabad so is Albany in New York.\r\nDegree relationship—Example— Warm: Hot as\r\n(B) Climate: Weather\r\n(A) Glue: Paste\r\n(D) Frown: Anger\r\n(C) Bright: Genius\r\nWarm is less hot and frown is less anger.\r\nSequence relationship—Spring: Summer at.\r\n(A) Thursday: Wednesday\r\n(B) Wednesday: Monday\r\n(C) Monday: Wednesday\r\n(D) Wednesday: Thursday\r\nSummer comes after Spring so does Thursday after Wednesday.\r\nAssociation relationship—Example—Devil: Wrong as\r\n(B) Slipper: State\r\n(A) Colour: Sidewalk\r\n(D) Picture: Bed\r\n', 'YES', '2020-06-16 11:07:35', '2020-06-16 11:07:58'),
(15, '735339995.jpeg', 'Processed', 'Unread', 'Oasis: Desert\r\n(A)\r\nLunch: Dessert\r\n(C)\r\nForest: Jungle\r\nAffluence: Poverty\r\nSad: Morose\r\n(A)\r\nRobust: Weak\r\n(C)\r\nGrass: Food\r\nWork: Tired\r\n(A)\r\nPlayer: Field\r\nRace: Fatigue\r\nCook: Eat\r\n(E)\r\nThin: Sparse\r\nTrace Tome\r\n(A)\r\nPreface: Book\r\n(D Corpulent: Obese\r\nSad: Melancholic\r\n(A) Over: Under\r\n(C) Weak: Robust\r\nFloor: Ceiling\r\n(E)\r\nFlurry: Confusion\r\n(A) Water: Thirst\r\nColour: Attraction\r\n(C)\r\nIntimidate: Fear\r\n(B)\r\n(D)\r\n(B)\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(O\r\n(D)\r\n(B)\r\n(D)\r\nInveigh: Inveigle\r\nOcean: Bay\r\nIngress: Egress\r\nGlad: Happy\r\nSwim: Pool\r\nBook: Knowledge\r\nPrologue: Epilogue\r\nTree: Tall\r\nJoy: Ecstasy\r\nBook: Writer\r\nNight: Sleep\r\nJob: Pay\r\n', 'YES', '2020-06-16 13:48:03', '2020-06-16 13:48:23'),
(16, '1253299990.jpeg', 'Processed', 'Unread', 'Turbid: Muddy\r\nRiver: Lake\r\n(A)\r\n(C) Bell: Ring\r\n(E) Deep: Shallow\r\nFresh: New\r\nDisease: Malaise\r\nEpical: Humorous\r\nStrident: Polite\r\n(E)\r\nWheel: Hub\r\n(A) Sea: Island\r\n(O Ruling Party: Cabinet\r\n(E) —j Watch: Needle\r\nSpeech: Peroration\r\nDinner: Dessert\r\n(A)\r\nArgument: Conclusion\r\n(E) Money: House\r\nDeath: Lament\r\nImpose: Fine\r\n(C) Make: Furniture\r\n(E) Learn: Lessorft\r\nVirus: Disease\r\n(B)\r\n(B)\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(B)\r\n(B)\r\n(A)\r\n(E)\r\nDiscussion: Fight\r\nSuggestion: Acceptance\r\nClothes: Gentleman\r\nTree: Darkness\r\nHuge: Colossal\r\nSupercilious: Meek\r\nIndigent: Affluent\r\nBody: Heart\r\nLife: Happiness\r\nCountry: Boundary\r\nStyle: Debate\r\nCast: Vote\r\nCelebrate: Centenary\r\nDesire: Success\r\nBombardment: Destruction\r\n', 'YES', '2020-06-16 13:57:46', '2020-06-16 13:58:01'),
(17, '885382850.jpeg', 'Processed', 'Read', 'Foot: Toe\r\n(A)\r\n(C)\r\n(E)\r\nBody: Legs.\r\nNail : Fingers\r\nLeaves: Tree\r\nZenith: Nadir\r\nSerious: Sober\r\nFat : Protein\r\nPeak: Foot\r\nGiggle: Chortle\r\nSmile: Grim-F\r\n(A)\r\nEmancipation: Bondage\r\nEdifice: Facade\r\nImmaculate: Spotless\r\nO) Fastidious: Punctilious\r\n(C) Mitigate: Pain\r\n(E) Ally: Lesson\r\nFever: Flush\r\nLiquid: Gas\r\n(A)\r\n(C) Wings: Flap\r\nCough: Cough\r\n(E)\r\nPistol: Shoot\r\n(B)\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(D)\r\n(B)\r\nBelly: Intestines\r\nHand : Fingers\r\nFood: Hungry\r\nMajestic: Sublime\r\nMelancholy: Antipathy\r\nInsipid: Charming\r\nCareless: Carefree\r\nAllay: Aggravate\r\nMalaria: Shiver\r\nRehearsal: Drama\r\nCatechism: Church\r\n(A)\r\n(C)\r\n(E)\r\nStone: Throw\r\nBall: Goal\r\nSword: Cut\r\n', 'YES', '2020-06-16 14:09:32', '2020-06-16 14:09:57'),
(18, '742168790.jpeg', 'Processed', 'Unread', 'Prelude: Symphony\r\n(A) Drama: Epilogue\r\n(C) Meal: Dessert\r\nO) Preamble: Constitution\r\nChains: Clang\r\n(A) Leaves: Twigs\r\nDoor: Lock\r\n(E) Wire: Snap\r\nLoud: Blatant\r\nHigh: Low\r\n(A)\r\nPenchant: Trenchant\r\n(E) Good: Bad\r\nEarth: Sun\r\n(A) Venus: Mars\r\n(O Sun: Galaxy\r\nUniverse: Pole-Star\r\n(E)\r\nRoom: Cell\r\nFort: Battlements\r\n(A)\r\nHall: Room\r\nBedroom: Bed\r\n(B)\r\n(D)\r\n(O\r\n(D)\r\n(B)\r\n(B)\r\n(D)\r\n(B)\r\nEpilogue: Prologue\r\nTicket: Show\r\nCoins: Jingle\r\nWolf: Roar\r\nCircle: Oval\r\nNoisome: Fetid\r\nPluto: Moon\r\nSun: Star\r\nArcade: Arbour\r\nBuilding: Office\r\n', 'YES', '2020-06-16 14:17:13', '2020-06-16 14:17:24'),
(19, '367216852.jpeg', 'Processed', 'Unread', 'Books are, by far, the most lasting product of human effort. Temples crumble into ruin. Pictures and\r\nstatues decay, but books survive. Time does not destroy the great thoughts which are as fresh today as when\r\nthey first passed through their author\'s mind. These thoughts speak to us through the printed page. The only\r\neffect of time has been to throw out of currency the bad products. Nothing in literature which is not good can\r\nlive for long. Good books have always helped man in various spheres of life. No wonder that the world keeps\r\n• its books with great care.\r\n', 'YES', '2020-06-16 14:34:54', '2020-06-16 14:35:07'),
(20, '725140562.jpeg', 'Processed', 'Unread', 'Of the product of human effort, books are the most\r\nO) Permanent\r\n(B)\r\nEnjoyable\r\n(C)\r\n(D)\r\nTime does not destroy books because they contain\r\nUseful material\r\n(A)\r\nHigh ideals\r\n(C)\r\n\"To throw out of currency\" means\r\nDestroy\r\n(A)\r\nExtinguish\r\nThe world keeps its books with care because\r\n(B)\r\n(O\r\n(D)\r\nImportant\r\nUseful\r\nSubject-matter for education\r\nGreat ideas\r\nPut out of use\r\nForget\r\n(A)\r\n(B)\r\nThey bring great ideas to us\r\nThey educate us\r\nThey make us successful\r\nThey help us in various spheres o! life\r\n', 'YES', '2020-06-16 14:39:52', '2020-06-16 14:40:07'),
(21, '899784260.jpeg', 'Processed', 'Unread', 'Passage 7\r\nAfter submitting his resignation, Albert came out and took the long narrow road leading to the\r\nrailway station which was one of the busiest roads in the city. Sad and depressed and worried about looking\r\nfor a new job, Albert looked around for a cigarette shop. He walked up to the end of the road but found no\r\ntobacconist. kt was odd that such a busy thoroughfare with thousands of people passing through (fid not even\r\nhave a single cigarette shop. He suddenly felt that it was no longer necessary for him to hunt for a job. He\r\ndecided to open a tobacco shop himself. It was bound to be profitable, he felt.\r\n', 'YES', '2020-06-16 15:03:12', '2020-06-16 15:03:36'),
(22, '592597511.jpeg', 'Processed', 'Unread', 'After submitting his resignation, Albert came out worried about\r\nO A job\r\n(B) The next available rain\r\n(C) A shelter\r\n(D) Cigarettes\r\nAlbert was sad and depressed because\r\nHe was not able to buy cigarettes\r\n(A)\r\nHe was worried about finding a job\r\n(B)\r\n(C) He had no money for the train journey\r\n@ He had to walk on a long road\r\nThere was no cigarette shop on that road because\r\nIt was a very narrow road\r\n(A)\r\nCigarette-shop owners do not make any profit\r\n(B)\r\nSmoking is banned in that area\r\n(C)\r\n(D Just by chance nobody had opened one on that road\r\nAlbert decided not to look for a new job because\r\nThere was no hope of finding a job\r\n(A)\r\nHe saw the possibility of self-employment\r\n(C) The thought of having to look for a job greatly distressed him\r\nHe did not want to work at all\r\n(D)\r\nA cigarette shop on a busy road was bound to be profitable because\r\nCigarettes are inexpensive items and people buy them willingly\r\n(A)\r\nO - A cigarette shop on a busy road would attract a large number of customers\r\nCigarette shops are known to make a great deal of profit\r\n(C)\r\n', 'YES', '2020-06-16 15:05:58', '2020-06-16 15:06:19'),
(23, '1628594025.jpeg', 'Processed', 'Read', 'Voice: Aphasia\r\n(A) Hearin : Ear\r\n(C)\r\nSleep: omnambulism\r\nSight; Blindness\r\nSwan: Cygnet\r\nO) Horse: Filly\r\nPig: Sty\r\n(E) Leaf: Flower\r\nReaper: Scythe\r\nSurgeon: Scalpel\r\nButcher: Sheep\r\n(E) Writer: Ink\r\nHassock: Kneeling\r\n(A)\r\nKitchen: Cooking\r\n(C) Field: Running\r\n(E)\r\nHearth: Cooking\r\nBarometer: Pressure\r\nHumidity: Hygrometer\r\nHeight: Pole\r\n(E)\r\nHeight: Depth\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(BY\r\n(B)\r\n(D)\r\nNose: Smell\r\nHunger: Starvation\r\nElephant: Goad\r\nTree: Forest\r\nBarber: Hair\r\nBatsman: Bat\r\nBedroom: Sleeping\r\nChair: Sitting\r\nBlood Circulation: Stethoscope\r\nSea: Wave\r\n', 'YES', '2020-06-19 08:49:58', '2020-06-19 09:40:34'),
(24, '94622589.jpeg', 'Processed', 'Read', 'øugte: souna\r\n(A) Horn: Head\r\nFlute: Hole\r\n(E) Drum: Hit\r\nSay: Assert\r\nRequest: Implore\r\n{8\r\nPaint: Describe\r\n(E) Solve: Sum\r\nGrain: Skin\r\n(A) Wheat: Barley\r\n(O Wood: Grain\r\n(E) Alphabet\r\nStaircase: Degrees\r\nO) Ladder: Rung\r\n(C) Tree: Trunk\r\n(E) Book: Leaves\r\nMascot: Ominous\r\n(A) Auspices: Auspicious\r\n(C) Game: Player\r\nVictory: Defeat\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\nHorn: Blow\r\nFlute: Blow\r\nTell: Narrate\r\nTea: Coffee\r\nWood: Table\r\nBook: Wrapper\r\nHouse: Storey\r\nTable: Legs\r\nLoss: Defeat\r\nBeginning: Introduction\r\n', 'YES', '2020-06-19 09:22:10', '2020-06-19 09:40:34'),
(26, '1101832829.jpeg', 'Processed', 'Unread', 'Those defenders of the tobacco industry who deny that there is a casual linkage between cigarette\r\nsmoking and many diseases all but\r\nthe connection.\r\nIgnore\r\n(C) Explain\r\nthe statistical evidence that very clearly demonstrates\r\nSignify\r\n(B)\r\n(D) Refute\r\nI have come to see the loss, I won \'t see any one\r\n2.\r\n(A) Except\r\n(D) Other\r\n(C) Or else\r\nand receives no order from the\r\nThis state is a colony, however, in most matters, it is\r\n3.\r\nmother country.\r\n(A) Distant\r\n(C) Submissive\r\nTake any apple\r\n4.\r\n(A) What\r\n(C) Which\r\nyou like.\r\nO) Autonomous\r\n(D) Amorphous\r\n(B) As\r\n0) That\r\nBy the middle of January, the river had become so choked with ice as to be\r\nsmallest of boats.\r\n(A) Inactive\r\nImpassable\r\n(B) Unreliable\r\n(D) Unattractive\r\nThey fired upon the enemy from behind the trees, walls and any other\r\n6.\r\neven for the\r\npoint they could\r\nfind.\r\nVantage\r\n(C) Exposed\r\nThe dog is\r\n7.\r\n(A The\r\nfaithful animal.\r\n(B) Indefensible\r\n(D) Definitive\r\n(B) Not\r\n(D) Very\r\nIn their most recent report to the shareholders, the directors\r\n8.\r\nfinancial information on\r\ninternational sales.\r\n(9 Distort\r\n(C) Invent\r\nMaria has been waiting for you\r\n9.\r\n(A) Till\r\n(C) For\r\n(B) Omit\r\n(D) Substitute\r\nmorning.\r\n(B) From\r\n(D Since\r\n\'O. The evil of class and race hatred must be eliminated while it is still in an\r\n(B) Amorphous\r\n(A) Independent\r\n(D) Uncultivated\r\n(O Embryonic\r\nstate.\r\nthe broad generalization concerning welfare recipients by noting that\r\nThe candidate later\r\n', 'YES', '2020-06-19 09:40:47', '2020-06-19 09:41:01'),
(27, '1083697721.jpeg', 'Processed', 'Unread', 'Book: Leaves\r\nTable: Legs\r\n(A)\r\ne) Rosary: Beads\r\nClassroom: Desks\r\n(E)\r\nPeacock: Pride\r\n(A) Goat: Kid\r\nO) Lion: Bravery\r\nLoan: Debt\r\n(E)\r\nPainter: Brush\r\nStudent: Paper\r\n(A)\r\nFarmer: Field\r\n(C)\r\n(E) Doctor: Medicine\r\nWool: Shear\r\nBicycle: Pedal\r\n(A)\r\n(C) Tree: Planted\r\nBell: Ring\r\n(E)\r\nWool: Cashmilon\r\nSheep: Grass\r\n(A)\r\n(C) Wood: Furniture\r\n(O Butter: Margarine\r\n(B)\r\n(D)\r\n(B)\r\n(D)\r\n(D)\r\n(B)\r\nO)\r\n(B)\r\n(D)\r\nTeacher: Books\r\nCountry: Government\r\nMan: Manikin\r\nMonkey: Man\r\nSculptor: Chisel\r\nWriter: Ink\r\nFan: Switch\r\nFeather: Pluck\r\nCloth; Dress\r\nPaper: Bamboo\r\n', 'YES', '2020-06-19 10:27:17', '2020-06-19 10:27:32');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
